# Generated by Django 2.1.7 on 2019-04-09 18:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timestapm',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 18, 51, 50, 6306, tzinfo=utc)),
        ),
    ]
