# Generated by Django 2.1.7 on 2019-04-11 17:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_timestapm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='timestapm',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 11, 17, 33, 19, 432336, tzinfo=utc)),
        ),
    ]
