# Generated by Django 2.1.7 on 2019-04-24 16:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190416_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timestapm',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 16, 20, 28, 93711, tzinfo=utc)),
        ),
    ]
