# Generated by Django 2.1.7 on 2019-04-24 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190424_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timestapm',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 16, 22, 14, 475937, tzinfo=utc)),
        ),
    ]
