# Generated by Django 2.1.7 on 2019-04-26 16:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190424_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timestapm',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 16, 23, 0, 277535, tzinfo=utc)),
        ),
    ]
