# Generated by Django 2.1.7 on 2019-04-26 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190426_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timestapm',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 18, 2, 57, 466618, tzinfo=utc)),
        ),
    ]
